/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Mostafa(R-34)
 */
public class Home extends javax.swing.JFrame {

    int account;

    /**
     * Creates new form JLoan
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon=new ImageIcon(getClass().getResource("/Image/money-2724241_1920.jpg"));
        Image image = icon.getImage();
        jDesktopPane = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        menuBar = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuOpenAccount = new javax.swing.JMenuItem();
        menuUpdateAccount = new javax.swing.JMenuItem();
        menuCloseAccount = new javax.swing.JMenuItem();
        menuBalance = new javax.swing.JMenu();
        menuDeposit = new javax.swing.JMenuItem();
        menuWithdrawal = new javax.swing.JMenuItem();
        menuCheckBalance = new javax.swing.JMenuItem();
        menuLoan = new javax.swing.JMenu();
        menuOpenLoan = new javax.swing.JMenuItem();
        menuPaymentLoan = new javax.swing.JMenuItem();
        menuCheckLoan = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        menuBalanceReport = new javax.swing.JMenuItem();
        menuLoanReport = new javax.swing.JMenuItem();
        menuQuit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 451, Short.MAX_VALUE)
        );

        menuFile.setText("Account");
        menuFile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuOpenAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        menuOpenAccount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuOpenAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Add_File_16px.png"))); // NOI18N
        menuOpenAccount.setText("Open Account");
        menuOpenAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenAccountActionPerformed(evt);
            }
        });
        menuFile.add(menuOpenAccount);

        menuUpdateAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuUpdateAccount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuUpdateAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Available_Updates_16px.png"))); // NOI18N
        menuUpdateAccount.setText("Update Account");
        menuUpdateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateAccountActionPerformed(evt);
            }
        });
        menuFile.add(menuUpdateAccount);

        menuCloseAccount.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuCloseAccount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCloseAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_File_Delete_16px.png"))); // NOI18N
        menuCloseAccount.setText("Close Account");
        menuCloseAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCloseAccountActionPerformed(evt);
            }
        });
        menuFile.add(menuCloseAccount);

        menuBar.add(menuFile);

        menuBalance.setText("Balance");
        menuBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalanceActionPerformed(evt);
            }
        });

        menuDeposit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuDeposit.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Deposit_16px.png"))); // NOI18N
        menuDeposit.setText("Deposit");
        menuDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDepositActionPerformed(evt);
            }
        });
        menuBalance.add(menuDeposit);

        menuWithdrawal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        menuWithdrawal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuWithdrawal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Withdrawal_16px.png"))); // NOI18N
        menuWithdrawal.setText("Withdrawal");
        menuWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuWithdrawalActionPerformed(evt);
            }
        });
        menuBalance.add(menuWithdrawal);

        menuCheckBalance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        menuCheckBalance.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCheckBalance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cashbook_16px.png"))); // NOI18N
        menuCheckBalance.setText("Check Balance");
        menuCheckBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheckBalanceActionPerformed(evt);
            }
        });
        menuBalance.add(menuCheckBalance);

        menuBar.add(menuBalance);

        menuLoan.setText("Loan");
        menuLoan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuOpenLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menuOpenLoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuOpenLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Open_16px.png"))); // NOI18N
        menuOpenLoan.setText("Open Loan");
        menuOpenLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpenLoanActionPerformed(evt);
            }
        });
        menuLoan.add(menuOpenLoan);

        menuPaymentLoan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuPaymentLoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuPaymentLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Card_Payment_16px.png"))); // NOI18N
        menuPaymentLoan.setText("Payment Loan");
        menuPaymentLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPaymentLoanActionPerformed(evt);
            }
        });
        menuLoan.add(menuPaymentLoan);

        menuCheckLoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuCheckLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Purchase_Order_16px.png"))); // NOI18N
        menuCheckLoan.setText("CheckLoan");
        menuCheckLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCheckLoanActionPerformed(evt);
            }
        });
        menuLoan.add(menuCheckLoan);

        menuBar.add(menuLoan);

        menuReport.setText("Report");
        menuReport.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        menuBalanceReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        menuBalanceReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuBalanceReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Report_Card_16px.png"))); // NOI18N
        menuBalanceReport.setText("Balance Report");
        menuBalanceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBalanceReportActionPerformed(evt);
            }
        });
        menuReport.add(menuBalanceReport);

        menuLoanReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menuLoanReport.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        menuLoanReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8_Cashbook_16px.png"))); // NOI18N
        menuLoanReport.setText("Loan Report");
        menuLoanReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoanReportActionPerformed(evt);
            }
        });
        menuReport.add(menuLoanReport);

        menuBar.add(menuReport);

        menuQuit.setText("Quit");
        menuQuit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        menuQuit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuQuitMouseClicked(evt);
            }
        });
        menuQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQuitActionPerformed(evt);
            }
        });
        menuBar.add(menuQuit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuBalanceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalanceReportActionPerformed
        BalanceCheck bCheck = new BalanceCheck();
        jDesktopPane.add(bCheck);
        bCheck.show();
    }//GEN-LAST:event_menuBalanceReportActionPerformed

    private void menuWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuWithdrawalActionPerformed
        Withdrawal withdraw = new Withdrawal();
        jDesktopPane.add(withdraw);
        withdraw.show();
    }//GEN-LAST:event_menuWithdrawalActionPerformed

    private void menuDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDepositActionPerformed

        Deposit dep = new Deposit();
        jDesktopPane.add(dep);
        dep.show();
    }//GEN-LAST:event_menuDepositActionPerformed

    private void menuCheckBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheckBalanceActionPerformed
        BalanceCheck bCheck = new BalanceCheck();
        jDesktopPane.add(bCheck);
        bCheck.show();
    }//GEN-LAST:event_menuCheckBalanceActionPerformed

    private void menuCloseAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCloseAccountActionPerformed
        account = Integer.parseInt(JOptionPane.showInputDialog(null, "Please Input Account Number"));

        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("delete from loan_managment where account_number = '" + account + "' ");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Account Number '" + account + "' is deleted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "There is no such record");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_menuCloseAccountActionPerformed

    private void menuUpdateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateAccountActionPerformed
        UpdateAccount ua = new UpdateAccount();
        jDesktopPane.add(ua);
        ua.show();
    }//GEN-LAST:event_menuUpdateAccountActionPerformed

    private void menuOpenAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenAccountActionPerformed
        OpenAccount newWin = new OpenAccount();
        jDesktopPane.add(newWin);
        newWin.show();
    }//GEN-LAST:event_menuOpenAccountActionPerformed

    private void menuOpenLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpenLoanActionPerformed
        Loan loan = new Loan();
        jDesktopPane.add(loan);
        loan.show();
    }//GEN-LAST:event_menuOpenLoanActionPerformed

    private void menuBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBalanceActionPerformed
        
    }//GEN-LAST:event_menuBalanceActionPerformed

    private void menuQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitActionPerformed
        
    }//GEN-LAST:event_menuQuitActionPerformed

    private void menuQuitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuQuitMouseClicked
        int x = JOptionPane.showConfirmDialog(rootPane, "Are You Sure Want To Exit?", "Confirmation", JOptionPane.OK_CANCEL_OPTION);
        if(x==JOptionPane.OK_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menuQuitMouseClicked

    private void menuPaymentLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPaymentLoanActionPerformed
        LoanPay lp = new LoanPay();
        jDesktopPane.add(lp);
        lp.show();
    }//GEN-LAST:event_menuPaymentLoanActionPerformed

    private void menuCheckLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCheckLoanActionPerformed
        CheckLoan cl = new CheckLoan();
        jDesktopPane.add(cl);
        cl.show();
    }//GEN-LAST:event_menuCheckLoanActionPerformed

    private void menuLoanReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoanReportActionPerformed
        CheckLoan cl = new CheckLoan();
        jDesktopPane.add(cl);
        cl.show();
    }//GEN-LAST:event_menuLoanReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu menuBalance;
    private javax.swing.JMenuItem menuBalanceReport;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuCheckBalance;
    private javax.swing.JMenuItem menuCheckLoan;
    private javax.swing.JMenuItem menuCloseAccount;
    private javax.swing.JMenuItem menuDeposit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuLoan;
    private javax.swing.JMenuItem menuLoanReport;
    private javax.swing.JMenuItem menuOpenAccount;
    private javax.swing.JMenuItem menuOpenLoan;
    private javax.swing.JMenuItem menuPaymentLoan;
    private javax.swing.JMenu menuQuit;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuUpdateAccount;
    private javax.swing.JMenuItem menuWithdrawal;
    // End of variables declaration//GEN-END:variables
}
