/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class LoanPay extends javax.swing.JInternalFrame {

    int account;
    String name;
    String father;
    String mobile;
    Double loan;
    Double payable;
    Double month;
    Double payment;
    Double cMonth;
    Double cPayment;
    Double dLoan;
    Double dMonth;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());

    /**
     * Creates new form OpenAccount
     */
    public LoanPay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeading = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        labelFather = new javax.swing.JLabel();
        tfFather = new javax.swing.JTextField();
        labelName3 = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        labelDeposit2 = new javax.swing.JLabel();
        tfDueLoan = new javax.swing.JTextField();
        labelWithdrawal1 = new javax.swing.JLabel();
        tfPayment = new javax.swing.JTextField();
        labelDeposit4 = new javax.swing.JLabel();
        tfDueMonth = new javax.swing.JTextField();
        labelWithdrawal2 = new javax.swing.JLabel();
        tfCMonth = new javax.swing.JTextField();
        labelWithdrawal3 = new javax.swing.JLabel();
        tfCPayment = new javax.swing.JTextField();
        labelDeposit3 = new javax.swing.JLabel();
        tfCDueLoan = new javax.swing.JTextField();
        labelDeposit5 = new javax.swing.JLabel();
        tfCDueMonth = new javax.swing.JTextField();
        labelName4 = new javax.swing.JLabel();
        tfLoan = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        labelCompany = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        AccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfAccount = new javax.swing.JTextField();
        ButtonCheck = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 0));

        labelHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeading.setText("Bank Managment System");

        ContentPane.setBackground(new java.awt.Color(204, 204, 0));
        ContentPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loan Payment:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30))); // NOI18N

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Full Name              :");

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        labelFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFather.setText("Father Name        :");

        tfFather.setEditable(false);
        tfFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfFather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFatherActionPerformed(evt);
            }
        });

        labelName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName3.setText("Mobile Number   :");

        tfMobile.setEditable(false);
        tfMobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileActionPerformed(evt);
            }
        });

        labelDeposit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit2.setText("Due Payable Loan:");

        tfDueLoan.setEditable(false);
        tfDueLoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfDueLoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDueLoanFocusLost(evt);
            }
        });
        tfDueLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDueLoanActionPerformed(evt);
            }
        });
        tfDueLoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDueLoanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDueLoanKeyTyped(evt);
            }
        });

        labelWithdrawal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal1.setText("Monthly Payable      :");

        tfPayment.setEditable(false);
        tfPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPaymentActionPerformed(evt);
            }
        });

        labelDeposit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit4.setText("Due Month           :");

        tfDueMonth.setEditable(false);
        tfDueMonth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfDueMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDueMonthFocusLost(evt);
            }
        });
        tfDueMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDueMonthActionPerformed(evt);
            }
        });
        tfDueMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDueMonthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDueMonthKeyTyped(evt);
            }
        });

        labelWithdrawal2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal2.setText("Pay for (Month)       :");

        tfCMonth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfCMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCMonthActionPerformed(evt);
            }
        });

        labelWithdrawal3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal3.setText("Payment Amount    :");

        tfCPayment.setEditable(false);
        tfCPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfCPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCPaymentActionPerformed(evt);
            }
        });

        labelDeposit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit3.setText("Current Due Loan   :");

        tfCDueLoan.setEditable(false);
        tfCDueLoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfCDueLoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCDueLoanFocusLost(evt);
            }
        });
        tfCDueLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCDueLoanActionPerformed(evt);
            }
        });
        tfCDueLoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCDueLoanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCDueLoanKeyTyped(evt);
            }
        });

        labelDeposit5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit5.setText("Current Due Month:");

        tfCDueMonth.setEditable(false);
        tfCDueMonth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfCDueMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfCDueMonthFocusLost(evt);
            }
        });
        tfCDueMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCDueMonthActionPerformed(evt);
            }
        });
        tfCDueMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCDueMonthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCDueMonthKeyTyped(evt);
            }
        });

        labelName4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName4.setText("Loan                       :");

        tfLoan.setEditable(false);
        tfLoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContentPaneLayout = new javax.swing.GroupLayout(ContentPane);
        ContentPane.setLayout(ContentPaneLayout);
        ContentPaneLayout.setHorizontalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelName4)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelName)
                        .addComponent(labelName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDeposit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelFather, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelDeposit2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMobile)
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFather)
                                    .addComponent(tfName)))
                            .addComponent(tfDueMonth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(tfDueLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDeposit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDeposit5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCDueMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCDueLoan)))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelWithdrawal1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelWithdrawal2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelWithdrawal3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ContentPaneLayout.setVerticalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFather)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDueLoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDueMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelWithdrawal1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelWithdrawal2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelWithdrawal3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelDeposit3)
                                .addComponent(tfCDueLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(labelName4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelDeposit5)
                                    .addComponent(tfCDueMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(labelDeposit2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDeposit4)
                        .addGap(8, 8, 8))))
        );

        ButtonPanel.setBackground(new java.awt.Color(204, 204, 0));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCalculateFocusLost(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        labelCompany.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelCompany.setText("All rights reserved by SNA Managment System");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnPay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPay.setText("Payment");
        btnPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnPayFocusLost(evt);
            }
        });
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(90, 90, 90))
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelCompany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCompany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AccountPanel.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Account Number:");

        tfAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAccountFocusLost(evt);
            }
        });

        ButtonCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonCheck.setText("Check");
        ButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfAccount)
                .addGap(18, 18, 18)
                .addComponent(ButtonCheck)
                .addGap(20, 20, 20))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(labelHeading))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ContentPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(AccountPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFatherActionPerformed

    private void tfMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        System.exit(0);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCalculateFocusLost

        calcFocusOn();
    }//GEN-LAST:event_btnCalculateFocusLost

    private void calcFocusOn() {
        if (tfDueLoan.getText().isEmpty()) {
            tfAccount.requestFocus();
        } else if (tfCMonth.getText().isEmpty()) {
            tfCMonth.requestFocus();
        }
    }
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        validCalc();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void validCalc() {
        if (tfDueLoan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Check Account Number First", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfCMonth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Number Of Pay Month", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            calculate();
        }
    }

    private void calculate() {
        loan = Double.parseDouble(tfLoan.getText());
        payable = Double.parseDouble(tfDueLoan.getText());
        month = Double.parseDouble(tfDueMonth.getText());
        payment = Double.parseDouble(tfPayment.getText());
        cMonth = Double.parseDouble(tfCMonth.getText());

        cPayment = payment * cMonth;
        dLoan = payable - cPayment;
        dMonth = month - cMonth;

        tfCPayment.setText(String.valueOf(cPayment));
    }

    private void tfAccountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAccountFocusLost

    }//GEN-LAST:event_tfAccountFocusLost

    private void ButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckActionPerformed

        if (tfAccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Account Number");
        } else {
            account = Integer.parseInt(tfAccount.getText());

            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;

            try {
                con = DatabaseConnection.getConnection();
                ps = con.prepareStatement("select account_number from loan where account_number=?");
                ps.setInt(1, account);
                rs = ps.executeQuery();
                if (rs.next()) {
                    loanCheck();
                } else {
                    JOptionPane.showMessageDialog(this, "No Record Found.");
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                    ps.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        }
    }//GEN-LAST:event_ButtonCheckActionPerformed

    private void loanCheck() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select month from loan where account_number = '" + account + "' ");
            while (rs.next()) {
                month = rs.getDouble("month");
            }
            if (month > 0) {
                loanBalSet();
            } else {
                JOptionPane.showMessageDialog(this, "Currently You Have No Loan");
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void loanBalSet() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select name, father_name, mobile_number, loan, payable, month,"
                    + " payment from loan_managment natural join loan"
                    + " where account_number = '" + account + "' ");
            while (rs.next()) {
                name = rs.getString("name");
                father = rs.getString("father_name");
                mobile = rs.getString("mobile_number");
                loan = rs.getDouble("loan");
                payable = rs.getDouble("payable");
                month = rs.getDouble("month");
                payment = rs.getDouble("payment");

                tfName.setText(name);
                tfFather.setText(father);
                tfMobile.setText(mobile);
                tfLoan.setText(Double.toString(loan));
                tfDueLoan.setText(Double.toString(payable));
                tfDueMonth.setText(Double.toString(month));
                tfPayment.setText(Double.toString(payment));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

    }
    private void tfDueLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDueLoanActionPerformed

    }//GEN-LAST:event_tfDueLoanActionPerformed

    private void tfDueLoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDueLoanKeyReleased

    }//GEN-LAST:event_tfDueLoanKeyReleased

    private void tfDueLoanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDueLoanKeyTyped

    }//GEN-LAST:event_tfDueLoanKeyTyped

    private void tfDueLoanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDueLoanFocusLost

    }//GEN-LAST:event_tfDueLoanFocusLost

    private void tfPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPaymentActionPerformed

    private void tfDueMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDueMonthFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDueMonthFocusLost

    private void tfDueMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDueMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDueMonthActionPerformed

    private void tfDueMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDueMonthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDueMonthKeyReleased

    private void tfDueMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDueMonthKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDueMonthKeyTyped

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void reset() {
        tfAccount.setText("");
        tfName.setText("");
        tfFather.setText("");
        tfMobile.setText("");
        tfLoan.setText("");
        tfDueLoan.setText("");
        tfDueMonth.setText("");
        tfPayment.setText("");
        tfCMonth.setText("");
        tfCPayment.setText("");
        tfCDueLoan.setText("");
        tfCDueMonth.setText("");
    }
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        if (tfCPayment.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You Didn't Pay Loan");
        } else {
            int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Please Input Account Number", account));
            PrintLoanPay plp = new PrintLoanPay();
            plp.display(x);
            plp.setLocationRelativeTo(null);
            plp.setVisible(true);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tfCMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCMonthActionPerformed

    private void tfCPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCPaymentActionPerformed

    private void tfCDueLoanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCDueLoanFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueLoanFocusLost

    private void tfCDueLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCDueLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueLoanActionPerformed

    private void tfCDueLoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCDueLoanKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueLoanKeyReleased

    private void tfCDueLoanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCDueLoanKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueLoanKeyTyped

    private void tfCDueMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfCDueMonthFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueMonthFocusLost

    private void tfCDueMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCDueMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueMonthActionPerformed

    private void tfCDueMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCDueMonthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueMonthKeyReleased

    private void tfCDueMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCDueMonthKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCDueMonthKeyTyped

    private void btnPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPayFocusLost
        calcFocusOn();
    }//GEN-LAST:event_btnPayFocusLost

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (tfCPayment.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Calculate First", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            paymentLoan();
        }
    }//GEN-LAST:event_btnPayActionPerformed

    private void tfLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLoanActionPerformed

    private void paymentLoan() {

        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("update loan set payable='" + dLoan + "', month='" + dMonth + "', cmonth='"+cMonth+"', cpayment='"+cPayment+"' ");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Payment Complated for " + cMonth + " month");

                tfCDueLoan.setText(String.valueOf(dLoan));
                tfCDueMonth.setText(String.valueOf(dMonth));
            } else {
                JOptionPane.showMessageDialog(this, "Payment failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JButton ButtonCheck;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JLabel labelDeposit2;
    private javax.swing.JLabel labelDeposit3;
    private javax.swing.JLabel labelDeposit4;
    private javax.swing.JLabel labelDeposit5;
    private javax.swing.JLabel labelFather;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName3;
    private javax.swing.JLabel labelName4;
    private javax.swing.JLabel labelWithdrawal1;
    private javax.swing.JLabel labelWithdrawal2;
    private javax.swing.JLabel labelWithdrawal3;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfCDueLoan;
    private javax.swing.JTextField tfCDueMonth;
    private javax.swing.JTextField tfCMonth;
    private javax.swing.JTextField tfCPayment;
    private javax.swing.JTextField tfDueLoan;
    private javax.swing.JTextField tfDueMonth;
    private javax.swing.JTextField tfFather;
    private javax.swing.JTextField tfLoan;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPayment;
    // End of variables declaration//GEN-END:variables
}
