/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class Loan extends javax.swing.JInternalFrame {

    int account;
    String name;
    String father;
    String mother;
    String mobile;
    String lDate;
    Double loan;
    Double interest;
    Double month;
    Double payment;
    Double payable;

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
    Calendar cal = Calendar.getInstance();

    /**
     * Creates new form OpenAccount
     */
    public Loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeading = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        labelFather = new javax.swing.JLabel();
        tfFather = new javax.swing.JTextField();
        labelName2 = new javax.swing.JLabel();
        tfMother = new javax.swing.JTextField();
        labelName3 = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        labelDeposit2 = new javax.swing.JLabel();
        tfLoan = new javax.swing.JTextField();
        labelWithdrawal = new javax.swing.JLabel();
        tfPayable = new javax.swing.JTextField();
        labelDate = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        labelWithdrawal1 = new javax.swing.JLabel();
        tfPayment = new javax.swing.JTextField();
        labelDeposit3 = new javax.swing.JLabel();
        tfInterest = new javax.swing.JTextField();
        labelDeposit4 = new javax.swing.JLabel();
        tfMonth = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnCalculate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        labelCompany = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        AccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfAccount = new javax.swing.JTextField();
        ButtonCheck = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 0));

        labelHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeading.setText("Bank Managment System");

        ContentPane.setBackground(new java.awt.Color(204, 204, 0));
        ContentPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loan:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30))); // NOI18N

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Full Name          :");

        tfName.setEditable(false);
        tfName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        labelFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFather.setText("Father Name     :");

        tfFather.setEditable(false);
        tfFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfFather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFatherActionPerformed(evt);
            }
        });

        labelName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName2.setText("Mother Name   :");

        tfMother.setEditable(false);
        tfMother.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotherActionPerformed(evt);
            }
        });

        labelName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName3.setText("Mobile Number :");

        tfMobile.setEditable(false);
        tfMobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileActionPerformed(evt);
            }
        });

        labelDeposit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit2.setText("Loan Amount       :");

        tfLoan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfLoan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfLoanFocusLost(evt);
            }
        });
        tfLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoanActionPerformed(evt);
            }
        });
        tfLoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfLoanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfLoanKeyTyped(evt);
            }
        });

        labelWithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal.setText("Total Payable        :");

        tfPayable.setEditable(false);
        tfPayable.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPayable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPayableActionPerformed(evt);
            }
        });

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDate.setText("Date                    :");

        labelWithdrawal1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal1.setText("Monthly Payment:");

        tfPayment.setEditable(false);
        tfPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPaymentActionPerformed(evt);
            }
        });

        labelDeposit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit3.setText("Interest Rate       :");

        tfInterest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfInterest.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfInterestFocusLost(evt);
            }
        });
        tfInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfInterestActionPerformed(evt);
            }
        });
        tfInterest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfInterestKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfInterestKeyTyped(evt);
            }
        });

        labelDeposit4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit4.setText("Payment Number:");

        tfMonth.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfMonthFocusLost(evt);
            }
        });
        tfMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMonthActionPerformed(evt);
            }
        });
        tfMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMonthKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMonthKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout ContentPaneLayout = new javax.swing.GroupLayout(ContentPane);
        ContentPane.setLayout(ContentPaneLayout);
        ContentPaneLayout.setHorizontalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfMother))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfFather))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMobile)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelWithdrawal1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(labelDeposit4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWithdrawal)
                            .addComponent(labelDeposit3)
                            .addComponent(labelDeposit2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfLoan)
                        .addComponent(tfPayable, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfInterest))))
        );
        ContentPaneLayout.setVerticalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDeposit2)
                            .addComponent(tfLoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFather)
                            .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeposit3)
                            .addComponent(tfInterest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDeposit4)
                        .addComponent(tfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfMother)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelWithdrawal1)
                        .addComponent(tfPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfMobile)
                        .addComponent(labelName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelWithdrawal)
                        .addComponent(tfPayable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        ButtonPanel.setBackground(new java.awt.Color(204, 204, 0));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnCalculate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCalculate.setText("Calculate");
        btnCalculate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnCalculateFocusLost(evt);
            }
        });
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSaveFocusLost(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        labelCompany.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelCompany.setText("All rights reserved by SNA Managment System");

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCompany)
                .addGap(54, 54, 54))
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCalculate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelCompany)
                .addContainerGap())
        );

        AccountPanel.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Account Number:");

        tfAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAccountFocusLost(evt);
            }
        });

        ButtonCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonCheck.setText("Check");
        ButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfAccount)
                .addGap(18, 18, 18)
                .addComponent(ButtonCheck)
                .addGap(20, 20, 20))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(labelHeading))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AccountPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFatherActionPerformed

    private void tfMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotherActionPerformed

    private void tfMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        System.exit(0);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCalculateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnCalculateFocusLost

        calcFocusOn();
    }//GEN-LAST:event_btnCalculateFocusLost

    private void calcFocusOn() {
        if (tfLoan.getText().isEmpty()) {
            tfLoan.requestFocus();
        } else if (tfInterest.getText().isEmpty()) {
            tfInterest.requestFocus();
        } else if (tfMonth.getText().isEmpty()) {
            tfMonth.requestFocus();
        }
    }
    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        validCalc();
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void validCalc() {
        if (tfLoan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Loan Amount", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfInterest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Interest Rate", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfMonth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Number Of Payment", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            calculate();
        }
    }

    private void calculate() {
        loan = Double.parseDouble(tfLoan.getText());
        interest = Double.parseDouble(tfInterest.getText());
        month = Double.parseDouble(tfMonth.getText());

        payable = loan + (loan * interest) / 100;
        payment = payable / month;

        tfPayment.setText(String.valueOf(payment));
        tfPayable.setText(String.valueOf(payable));
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (tfAccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter Account Number", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please Select date", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            validSave();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void validSave() {
        if (tfLoan.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Loan Amount", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfInterest.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Interest Rate", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfMonth.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Number Of Payment", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            privLoanCheck();
        }
    }

    private void privLoanCheck() {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            con = DatabaseConnection.getConnection();
            ps = con.prepareStatement("select account_number from loan where account_number=?");
            ps.setInt(1, account);
            rs = ps.executeQuery();
            if (rs.next()) {
                upLoanCheck();
            } else {
                calculate();
                saveData();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                ps.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void upLoanCheck() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select loan from loan where account_number = '" + account + "' ");
            while (rs.next()) {
                loan = rs.getDouble("loan");
            }
            if (loan > 0) {
                JOptionPane.showMessageDialog(this, "You aren't Eligible For Loan");
            } else {
                calculate();
                upLoan();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void saveData() {
        lDate = sdf.format(dateChooser.getDate());

        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("insert into loan(account_number, loan, interest, month, payment, payable, ldate)"
                    + " values('" + account + "','" + loan + "','" + interest + "','" + month + "','" + payment + "',"
                    + "'" + payable + "', '" + lDate + "') ");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Saved");
            } else {
                JOptionPane.showMessageDialog(this, "Save failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void upLoan() {
        lDate = sdf.format(dateChooser.getDate());
        
        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("update loan set loan='"+loan+"', interest='"+interest+"', month='"+month+"',"
                    + " payment='"+payment+"', payable='"+payable+"', ldate='"+lDate+"' ");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Saved");
            } else {
                JOptionPane.showMessageDialog(this, "Save failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }
    private void tfAccountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAccountFocusLost

    }//GEN-LAST:event_tfAccountFocusLost

    private void ButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckActionPerformed

        if (tfAccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Account Number");
        } else {
            account = Integer.parseInt(tfAccount.getText());

            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;

            try {
                con = DatabaseConnection.getConnection();
                ps = con.prepareStatement("select account_number from loan_managment where account_number=?");
                ps.setInt(1, account);
                rs = ps.executeQuery();
                if (rs.next()) {
                    loanCheck();
                } else {
                    JOptionPane.showMessageDialog(this, "<html><p>No Record Found.</p><p>Please Create New Account<p></html>");
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                    ps.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        }
    }//GEN-LAST:event_ButtonCheckActionPerformed

    private void loanCheck() {
        Connection con = null;
        PreparedStatement ps = null;
        ResultSet rs = null;

        try {
            con = DatabaseConnection.getConnection();
            ps = con.prepareStatement("select account_number from loan where account_number=?");
            ps.setInt(1, account);
            rs = ps.executeQuery();
            if (rs.next()) {
                loanBalCheck();
            } else {
                selectUpVal();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                ps.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void loanBalCheck() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select loan from loan where account_number = '" + account + "' ");
            while (rs.next()) {
                loan = rs.getDouble("loan");
            }
            if (loan > 0) {
                JOptionPane.showMessageDialog(this, "You aren't Eligible For Loan");
            } else {
                loanBalSet();
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void loanBalSet() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select name, father_name, mother_name, mobile_number, loan, interest, month,"
                    + " payment, payable from loan_managment natural join loan"
                    + " where account_number = '" + account + "' ");
            while (rs.next()) {
                name = rs.getString("name");
                father = rs.getString("father_name");
                mother = rs.getString("mother_name");
                mobile = rs.getString("mobile_number");
                loan = rs.getDouble("loan");
                interest = rs.getDouble("interest");
                month = rs.getDouble("month");
                payment = rs.getDouble("payment");
                payable = rs.getDouble("payable");

                tfName.setText(name);
                tfFather.setText(father);
                tfMother.setText(mother);
                tfMobile.setText(mobile);
                tfLoan.setText(Double.toString(loan));
                tfInterest.setText(Double.toString(interest));
                tfMonth.setText(Double.toString(month));
                tfPayment.setText(Double.toString(payment));
                tfPayable.setText(Double.toString(payable));
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void selectUpVal() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select name, father_name, mother_name, mobile_number "
                    + "from loan_managment where account_number = '" + account + "' ");
            while (rs.next()) {
                name = rs.getString("name");
                father = rs.getString("father_name");
                mother = rs.getString("mother_name");
                mobile = rs.getString("mobile_number");

                tfName.setText(name);
                tfFather.setText(father);
                tfMother.setText(mother);
                tfMobile.setText(mobile);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }
    private void tfLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoanActionPerformed

    }//GEN-LAST:event_tfLoanActionPerformed

    private void tfLoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoanKeyReleased

    }//GEN-LAST:event_tfLoanKeyReleased

    private void tfLoanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfLoanKeyTyped

    }//GEN-LAST:event_tfLoanKeyTyped

    private void tfPayableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPayableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPayableActionPerformed

    private void tfLoanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfLoanFocusLost

    }//GEN-LAST:event_tfLoanFocusLost

    private void tfPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPaymentActionPerformed

    private void tfInterestFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfInterestFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInterestFocusLost

    private void tfInterestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfInterestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInterestActionPerformed

    private void tfInterestKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInterestKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInterestKeyReleased

    private void tfInterestKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInterestKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfInterestKeyTyped

    private void tfMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfMonthFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMonthFocusLost

    private void tfMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMonthActionPerformed

    private void tfMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMonthKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMonthKeyReleased

    private void tfMonthKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMonthKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMonthKeyTyped

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void reset() {
        tfAccount.setText("");
        tfName.setText("");
        tfFather.setText("");
        tfMother.setText("");
        tfMobile.setText("");
        dateChooser.setCalendar(null);
        tfLoan.setText("");
        tfInterest.setText("");
        tfMonth.setText("");
        tfPayment.setText("");
        tfPayable.setText("");
    }
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Please Input Account Number", account));
        PrintLoan pl = new PrintLoan();
        pl.display(x);
        pl.setLocationRelativeTo(null);
        pl.setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusLost

        if (tfAccount.getText().isEmpty()) {
            tfAccount.requestFocus();
        } else if (dateChooser.getDate() == null) {
            dateChooser.requestFocus();
        } else {
            calcFocusOn();
        }
    }//GEN-LAST:event_btnSaveFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JButton ButtonCheck;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JButton btnCalculate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDeposit2;
    private javax.swing.JLabel labelDeposit3;
    private javax.swing.JLabel labelDeposit4;
    private javax.swing.JLabel labelFather;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelName3;
    private javax.swing.JLabel labelWithdrawal;
    private javax.swing.JLabel labelWithdrawal1;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfFather;
    private javax.swing.JTextField tfInterest;
    private javax.swing.JTextField tfLoan;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfMonth;
    private javax.swing.JTextField tfMother;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfPayable;
    private javax.swing.JTextField tfPayment;
    // End of variables declaration//GEN-END:variables
}
