/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mostafa
 */
public class NewUser extends javax.swing.JFrame {

    String name, email, user, pass;

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldUser = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ButtonRegister = new javax.swing.JButton();
        ButtonReset = new javax.swing.JButton();
        ButtonSign = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("New User Register");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name");

        TextFieldName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");

        TextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("User Name");

        TextFieldUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        ButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonRegister.setText("Register");
        ButtonRegister.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ButtonRegisterFocusLost(evt);
            }
        });
        ButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterActionPerformed(evt);
            }
        });

        ButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonReset.setText("Reset");
        ButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonResetActionPerformed(evt);
            }
        });

        ButtonSign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ButtonSign.setText("Already have an account? Sign in");
        ButtonSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignActionPerformed(evt);
            }
        });

        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/turkey-3134702_1920.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(82, 82, 82)
                .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(TextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(ButtonRegister))
            .addGroup(layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(ButtonSign))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(ButtonReset))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(TextFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(ButtonRegister)
                .addGap(25, 25, 25)
                .addComponent(ButtonSign))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(ButtonReset))
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel6)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignActionPerformed
        dispose();
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }//GEN-LAST:event_ButtonSignActionPerformed

    private void ButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterActionPerformed
        saveAndValid();
    }//GEN-LAST:event_ButtonRegisterActionPerformed

    private void saveAndValid() {
        if (TextFieldName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Your Full Name", "User Registration", JOptionPane.INFORMATION_MESSAGE);
        } else if (TextFieldEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Your Email", "User Registration", JOptionPane.INFORMATION_MESSAGE);
        } else if (TextFieldUser.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Your User Name", "User Registration", JOptionPane.INFORMATION_MESSAGE);
        } else if (PasswordField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Your Password", "User Registration", JOptionPane.INFORMATION_MESSAGE);
        } else {
            saveRegInfo();
        }
    }

    private void saveRegInfo() {
        getValues();

        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select * from login where email='" + email + "'");
            if (rs.next() == true) {
                JOptionPane.showMessageDialog(this, "Already Registered", "Alert", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int ctr = 0;
                ctr = stm.executeUpdate("insert into login(name, email, user_name, password)"
                        + "values('" + name + "', '" + email + "', '" + user + "', '" + pass + "')");
                if (ctr > 0) {
                    JOptionPane.showMessageDialog(this, "Saved");
                } else {
                    JOptionPane.showMessageDialog(this, "Save failed", "Error", JOptionPane.ERROR);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
                rs.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void getValues() {
        name = TextFieldName.getText();
        email = TextFieldEmail.getText();
        user = TextFieldUser.getText();
        pass = PasswordField.getText();
    }
    private void ButtonRegisterFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ButtonRegisterFocusLost
        valid();
    }//GEN-LAST:event_ButtonRegisterFocusLost

    private void valid() {
        if (TextFieldName.getText().isEmpty()) {
            TextFieldName.requestFocus();
        } else if (TextFieldEmail.getText().isEmpty()) {
            TextFieldEmail.requestFocus();
        } else if (TextFieldUser.getText().isEmpty()) {
            TextFieldUser.requestFocus();
        } else if (TextFieldUser.getText().isEmpty()) {
            TextFieldUser.requestFocus();
        } else if (PasswordField.getText().isEmpty()) {
            PasswordField.requestFocus();
        }
    }
    private void ButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonResetActionPerformed
        reset();
    }//GEN-LAST:event_ButtonResetActionPerformed

    private void reset() {
        TextFieldName.setText("");
        TextFieldEmail.setText("");
        TextFieldUser.setText("");
        PasswordField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRegister;
    private javax.swing.JButton ButtonReset;
    private javax.swing.JButton ButtonSign;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
