/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class OpenAccount extends javax.swing.JInternalFrame {

    int account;
    String name;
    String father;
    String mother;
    String mobile;
    String address;
    String nid;
    String dob;
    String type;
    Double deposit;
    Double balance;
    String date;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());

    /**
     * Creates new form OpenAccount
     */
    public OpenAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        labelHeading = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelType = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        labelDeposit = new javax.swing.JLabel();
        tfNid = new javax.swing.JTextField();
        tfBalance = new javax.swing.JTextField();
        labelWithdrawal = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        RadioCurrent = new javax.swing.JRadioButton();
        RadioSaving = new javax.swing.JRadioButton();
        labelDeposit1 = new javax.swing.JLabel();
        labelDeposit2 = new javax.swing.JLabel();
        tfDeposit = new javax.swing.JTextField();
        birthDate = new com.toedter.calendar.JDateChooser();
        labelFather = new javax.swing.JLabel();
        tfFather = new javax.swing.JTextField();
        labelName2 = new javax.swing.JLabel();
        tfMother = new javax.swing.JTextField();
        labelName3 = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        btnReset = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        labelCompany = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));

        labelHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeading.setText("Bank Managment System");

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Create Account:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30))); // NOI18N

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Full Name          :");

        labelAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAddress.setText("Address              :");

        labelType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelType.setText("Account Type  :");

        tfName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        tfAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        labelDeposit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit.setText("NID                     :");

        tfNid.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tfBalance.setEditable(false);
        tfBalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBalanceActionPerformed(evt);
            }
        });

        labelWithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal.setText("Balance             :");

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDate.setText("Date                  :");

        buttonGroup.add(RadioCurrent);
        RadioCurrent.setText("Current");

        buttonGroup.add(RadioSaving);
        RadioSaving.setText("Saving");

        labelDeposit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit1.setText("Date Of Barth :");

        labelDeposit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit2.setText("Deposit             :");

        tfDeposit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDepositActionPerformed(evt);
            }
        });
        tfDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfDepositKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDepositKeyTyped(evt);
            }
        });

        labelFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFather.setText("Father Name     :");

        tfFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfFather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFatherActionPerformed(evt);
            }
        });

        labelName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName2.setText("Mother Name   :");

        tfMother.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotherActionPerformed(evt);
            }
        });

        labelName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName3.setText("Mobile Number :");

        tfMobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(labelDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfNid, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tfMother, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(tfMobile)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFather))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(labelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeposit2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(tfBalance)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDeposit1)
                            .addComponent(labelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(RadioCurrent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(RadioSaving))
                            .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addGap(76, 76, 76))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeposit1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelType, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioCurrent)
                            .addComponent(RadioSaving)
                            .addComponent(tfFather)
                            .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDeposit2)
                            .addComponent(tfDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMother)
                            .addComponent(labelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelWithdrawal)
                            .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMobile)
                            .addComponent(labelName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfAddress)
                                .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSaveFocusLost(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Display & Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        labelCompany.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelCompany.setText("All rights reserved by SNA Managment System");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExit))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(labelCompany)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelCompany)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(labelHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHeading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void tfFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFatherActionPerformed

    private void tfMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotherActionPerformed

    private void tfMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        resetComp();

    }//GEN-LAST:event_btnResetActionPerformed

    private void resetComp() {
        tfName.setText("");
        tfFather.setText("");
        tfMother.setText("");
        tfMobile.setText("");
        tfAddress.setText("");
        tfNid.setText("");
        birthDate.setCalendar(null);
        buttonGroup.clearSelection();
        tfDeposit.setText("");
        tfBalance.setText("");
        dateChooser.setCalendar(null);
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        System.exit(0);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaveFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSaveFocusLost
        focusOn();
    }//GEN-LAST:event_btnSaveFocusLost

    private void focusOn() {
        if (tfName.getText().isEmpty()) {
            tfName.requestFocus();
        } else if (tfFather.getText().isEmpty()) {
            tfFather.requestFocus();
        } else if (tfMother.getText().isEmpty()) {
            tfMother.requestFocus();
        } else if (tfMobile.getText().isEmpty()) {
            tfMobile.requestFocus();
        } else if (tfAddress.getText().isEmpty()) {
            tfAddress.requestFocus();
        } else if (tfNid.getText().isEmpty()) {
            tfNid.requestFocus();
        } else if (birthDate.getDate() == null) {
            birthDate.requestFocus();
        } else if (buttonGroup.getSelection() == null) {
            RadioCurrent.requestFocus();
        } else if (tfDeposit.getText().isEmpty()) {
            tfDeposit.requestFocus();
        } else if (Integer.parseInt(tfDeposit.getText()) < 500) {
            tfDeposit.requestFocus();
        } else if (dateChooser.getDate() == null) {
            dateChooser.requestFocus();
        }
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        validAndSave();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void validAndSave() {
        if (tfName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Full Name", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfFather.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Father Name", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfMother.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Mother Name", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfMobile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Mobile Number", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfAddress.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Address", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfNid.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input National ID", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (birthDate.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please Input Date of Birth", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (buttonGroup.getSelection() == null) {
            JOptionPane.showMessageDialog(null, "Please Select Account Type", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (tfDeposit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Deposit Minimum Amount", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (Integer.parseInt(tfDeposit.getText()) < 500) {
            JOptionPane.showMessageDialog(null, "Please Deposit Minimum 500 Taka", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please Select date", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            saveData();
            displayAccountNo();
        }
    }

    private void saveData() {
        getValues();

        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("insert into loan_managment(name, father_name, mother_name, mobile_number, "
                    + "address, nid, dob, account_type, balance, date, deposit)"
                    + " values('" + name + "','" + father + "','" + mother + "','" + mobile + "','" + address + "','" + nid + "', '" + dob + "',"
                    + "'" + type + "','" + balance + "', '" + date + "', '" + deposit + "') ");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Saved");
                resetComp();
            } else {
                JOptionPane.showMessageDialog(this, "Save failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void getValues() {
        name = tfName.getText();
        father = tfFather.getText();
        mother = tfMother.getText();
        mobile = tfMobile.getText();
        address = tfAddress.getText();
        nid = tfNid.getText();
        dob = sdf.format(birthDate.getDate());
        if (RadioCurrent.isSelected()) {
            type = RadioCurrent.getText();
        } else {
            type = RadioSaving.getText();
        }
        deposit = Double.valueOf(tfDeposit.getText());
        balance = deposit;
        date = sdf.format(dateChooser.getDate());
    }

    private void displayAccountNo() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("SELECT account_number FROM loan_managment where name= '" + name + "' ");
            while (rs.next()) {
                account = rs.getInt("account_number");
                JOptionPane.showMessageDialog(null, "Your Account Number is " + account);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Please Input Account Number", account));
        PrintOpenInfo pf = new PrintOpenInfo();
        pf.display(x);
        pf.setLocationRelativeTo(null);
        pf.setVisible(true);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tfBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBalanceActionPerformed

    private void tfDepositKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDepositKeyTyped

    }//GEN-LAST:event_tfDepositKeyTyped

    private void tfDepositKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDepositKeyReleased
        tfBalance.setText(tfDeposit.getText());
    }//GEN-LAST:event_tfDepositKeyReleased

    private void tfDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDepositActionPerformed

    }//GEN-LAST:event_tfDepositActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioCurrent;
    private javax.swing.JRadioButton RadioSaving;
    private com.toedter.calendar.JDateChooser birthDate;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDeposit;
    private javax.swing.JLabel labelDeposit1;
    private javax.swing.JLabel labelDeposit2;
    private javax.swing.JLabel labelFather;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelName3;
    private javax.swing.JLabel labelType;
    private javax.swing.JLabel labelWithdrawal;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfBalance;
    private javax.swing.JTextField tfDeposit;
    private javax.swing.JTextField tfFather;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfMother;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfNid;
    // End of variables declaration//GEN-END:variables
}
