/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankapp;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Mostafa
 */
public class Withdrawal extends javax.swing.JInternalFrame {

    int account;
    String name;
    String father;
    String mother;
    String mobile;
    Double withdraw;
    Double balance;
    String date;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());

    /**
     * Creates new form OpenAccount
     */
    public Withdrawal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHeading = new javax.swing.JLabel();
        ContentPane = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        labelFather = new javax.swing.JLabel();
        tfFather = new javax.swing.JTextField();
        labelName2 = new javax.swing.JLabel();
        tfMother = new javax.swing.JTextField();
        labelName3 = new javax.swing.JLabel();
        tfMobile = new javax.swing.JTextField();
        labelDeposit2 = new javax.swing.JLabel();
        tfWithdrawal = new javax.swing.JTextField();
        labelWithdrawal = new javax.swing.JLabel();
        tfBalance = new javax.swing.JTextField();
        labelDate = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        ButtonPanel = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnWithdrawal = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        labelCompany = new javax.swing.JLabel();
        AccountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfAccount = new javax.swing.JTextField();
        ButtonCheck = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 102, 102));

        labelHeading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        labelHeading.setText("Bank Managment System");

        ContentPane.setBackground(new java.awt.Color(204, 204, 204));
        ContentPane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Withdrawal:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 30))); // NOI18N

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Full Name          :");

        tfName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameActionPerformed(evt);
            }
        });

        labelFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFather.setText("Father Name     :");

        tfFather.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfFather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFatherActionPerformed(evt);
            }
        });

        labelName2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName2.setText("Mother Name   :");

        tfMother.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMotherActionPerformed(evt);
            }
        });

        labelName3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName3.setText("Mobile Number :");

        tfMobile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMobileActionPerformed(evt);
            }
        });

        labelDeposit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDeposit2.setText("Withdrawal    :");

        tfWithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfWithdrawal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfWithdrawalFocusLost(evt);
            }
        });
        tfWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWithdrawalActionPerformed(evt);
            }
        });
        tfWithdrawal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfWithdrawalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfWithdrawalKeyTyped(evt);
            }
        });

        labelWithdrawal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelWithdrawal.setText("Balance           :");

        tfBalance.setEditable(false);
        tfBalance.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBalanceActionPerformed(evt);
            }
        });

        labelDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDate.setText("Date                :");

        javax.swing.GroupLayout ContentPaneLayout = new javax.swing.GroupLayout(ContentPane);
        ContentPane.setLayout(ContentPaneLayout);
        ContentPaneLayout.setHorizontalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfMother, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(tfMobile)))
                    .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentPaneLayout.createSequentialGroup()
                            .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfFather))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ContentPaneLayout.createSequentialGroup()
                            .addComponent(labelName)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelWithdrawal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeposit2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfWithdrawal)
                            .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContentPaneLayout.setVerticalGroup(
            ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentPaneLayout.createSequentialGroup()
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ContentPaneLayout.createSequentialGroup()
                                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfFather)
                                            .addComponent(labelFather, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(9, 9, 9))
                                    .addGroup(ContentPaneLayout.createSequentialGroup()
                                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelDeposit2)
                                            .addComponent(tfWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labelWithdrawal)
                                            .addComponent(tfBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfMother)
                                    .addComponent(labelName2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ContentPaneLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ContentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMobile)
                            .addComponent(labelName3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        ButtonPanel.setBackground(new java.awt.Color(204, 204, 204));
        ButtonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnWithdrawal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnWithdrawal.setText("Withdraw");
        btnWithdrawal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnWithdrawalFocusLost(evt);
            }
        });
        btnWithdrawal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawalActionPerformed(evt);
            }
        });

        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrint.setText("Display & Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        labelCompany.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        labelCompany.setText("All rights reserved by SNA Managment System");

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(labelCompany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnWithdrawal)
                .addGap(33, 33, 33)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(34, 34, 34))
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdrawal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelCompany)
                .addContainerGap())
        );

        AccountPanel.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Account Number:");

        tfAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tfAccount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfAccountFocusLost(evt);
            }
        });

        ButtonCheck.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonCheck.setText("Check");
        ButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccountPanelLayout = new javax.swing.GroupLayout(AccountPanel);
        AccountPanel.setLayout(AccountPanelLayout);
        AccountPanelLayout.setHorizontalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(ButtonCheck)
                .addGap(20, 20, 20))
        );
        AccountPanelLayout.setVerticalGroup(
            AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(labelHeading))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHeading)
                .addGap(6, 6, 6)
                .addComponent(AccountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameActionPerformed

    private void tfFatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFatherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFatherActionPerformed

    private void tfMotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMotherActionPerformed

    private void tfMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMobileActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        //        System.exit(0);
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnWithdrawalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnWithdrawalFocusLost
        focusOn();
    }//GEN-LAST:event_btnWithdrawalFocusLost

    private void focusOn() {
        if (tfAccount.getText().isEmpty()) {
            tfAccount.requestFocus();
        } else if (tfName.getText().isEmpty()) {
            tfName.requestFocus();
        } else if (tfFather.getText().isEmpty()) {
            tfFather.requestFocus();
        } else if (tfMother.getText().isEmpty()) {
            tfMother.requestFocus();
        } else if (tfMobile.getText().isEmpty()) {
            tfMobile.requestFocus();
        }
    }
    private void btnWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawalActionPerformed
        validAndSave();
    }//GEN-LAST:event_btnWithdrawalActionPerformed

    private void validAndSave() {
        if (tfAccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Account Number First");
        } else if (tfWithdrawal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Input Minimum Ammount", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (Integer.parseInt(tfWithdrawal.getText()) < 500) {
            JOptionPane.showMessageDialog(null, "You cannot withdraw below 500 Taka", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (Integer.parseInt(tfWithdrawal.getText()) > balance) {
            JOptionPane.showMessageDialog(null, "Insufficient Balance", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else if (dateChooser.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please Input Date", "Loan System", JOptionPane.INFORMATION_MESSAGE);
        } else {
            saveData();
        }
    }

    private void saveData() {
        getValues();

        Connection con = null;
        Statement stm = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            int ctr = 0;
            ctr = stm.executeUpdate("update loan_managment set withdrawal='" + withdraw + "', balance='" + balance + "', date='" + date + "'"
                    + " where account_number='" + account + "'");
            if (ctr > 0) {
                JOptionPane.showMessageDialog(this, "Withdrawal");
            } else {
                JOptionPane.showMessageDialog(this, "Withdrawal failed", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }

    private void getValues() {
        withdraw = Double.valueOf(tfWithdrawal.getText());
        balance = balance - withdraw;
        date = sdf.format(dateChooser.getDate());
    }
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        if (tfWithdrawal.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "You Didn't deposit");
        } else {
            int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Please Input Account Number", account));
            PrintWithdraw pw = new PrintWithdraw();
            pw.display(x);
            pw.setLocationRelativeTo(null);
            pw.setVisible(true);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tfAccountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfAccountFocusLost

    }//GEN-LAST:event_tfAccountFocusLost

    private void ButtonCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckActionPerformed
        if (tfAccount.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Enter Account Number");
        } else {
            account = Integer.parseInt(tfAccount.getText());

            Connection con = null;
            PreparedStatement ps = null;
            ResultSet rs = null;

            try {
                con = DatabaseConnection.getConnection();
                ps = con.prepareStatement("select account_number from loan_managment where account_number=?");
                ps.setInt(1, account);
                rs = ps.executeQuery();
                if (rs.next()) {
                    selectUpVal();
                } else {
                    JOptionPane.showMessageDialog(this, "There is no such record");
                }
            } catch (Exception e) {
                e.printStackTrace();
            } finally {
                try {
                    con.close();
                    ps.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            }
        }
    }//GEN-LAST:event_ButtonCheckActionPerformed

    private void selectUpVal() {
        Connection con = null;
        Statement stm = null;
        ResultSet rs = null;
        try {
            con = DatabaseConnection.getConnection();
            stm = con.createStatement();
            rs = stm.executeQuery("select name, father_name, mother_name, mobile_number, balance "
                    + "from loan_managment where account_number = '" + account + "' ");
            while (rs.next()) {
                name = rs.getString("name");
                father = rs.getString("father_name");
                mother = rs.getString("mother_name");
                mobile = rs.getString("mobile_number");
                balance = rs.getDouble("balance");

                tfName.setText(name);
                tfFather.setText(father);
                tfMother.setText(mother);
                tfMobile.setText(mobile);
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                con.close();
                stm.close();
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }
    }
    private void tfWithdrawalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWithdrawalActionPerformed

    }//GEN-LAST:event_tfWithdrawalActionPerformed

    private void tfWithdrawalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWithdrawalKeyReleased

    }//GEN-LAST:event_tfWithdrawalKeyReleased

    private void tfWithdrawalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWithdrawalKeyTyped

    }//GEN-LAST:event_tfWithdrawalKeyTyped

    private void tfBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBalanceActionPerformed

    private void tfWithdrawalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfWithdrawalFocusLost
        withdraw = Double.valueOf(tfWithdrawal.getText());
        tfBalance.setText(Double.toString(balance - withdraw));
    }//GEN-LAST:event_tfWithdrawalFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccountPanel;
    private javax.swing.JButton ButtonCheck;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel ContentPane;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnWithdrawal;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCompany;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelDeposit2;
    private javax.swing.JLabel labelFather;
    private javax.swing.JLabel labelHeading;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelName2;
    private javax.swing.JLabel labelName3;
    private javax.swing.JLabel labelWithdrawal;
    private javax.swing.JTextField tfAccount;
    private javax.swing.JTextField tfBalance;
    private javax.swing.JTextField tfFather;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfMother;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfWithdrawal;
    // End of variables declaration//GEN-END:variables
}
